### ISSUE TITLE
Unable to read specified file

### ISSUE THREAD

**Issue by aaalik** [codebox/bayesian-classifier#11]
when I am trying to classify I got an error like this

`Unable to read specified file "surat-izin.jpg.txt", the error message was: object of type 'filter' has no len()`

what does it mean?

**Comment by codebox** [comment]
It sounds like you are running the code using Python3 - this code was designed to run with Python2. You could try converting the code using [2to3](https://docs.python.org/2/library/2to3.html) or running with python2 if you have it installed.
