### ISSUE TITLE
diffculties in understanding the code

### ISSUE THREAD

**Issue by monika21089** [codebox/bayesian-classifier#2]
sir actually i am a beginner in python programming.so i am having problem in understanding that how am i going to train my data using the code and classify? can u explain it to me ?

**Comment by codebox** [comment]
Did you check the README file? If you just want to use the utility you
don't really need to understand the code, just follow the instrucitons in
the docs. If there is something specific in the code that you don't
understand then let me know which part is causing you trouble and I will
try to help
